### ISSUE TITLE
[FEATURE] Give second V2 another ability

### ISSUE THREAD

**Issue by PrinceKasaii** [eternalUnion/UltraPain#14]
# Feature

Make it so he can CHARGEBACK you. If coins are shot too early after he sends them flying through the air, they will turn red as if he shot them, and target you instead.

Configurable variables could include changing how much time the coins need to fly before they're safe to shoot, as well as how big the hitbox of coins are during this time period to make it easier or harder for chargebacks.

An ability on top of this would include an option to deliberately throw a coin in front of him as soon as you swap to and are able to fire a hitscan weapon like a revolver, so it shields him from the shot.

# Usage

This gives him another defensive and/or disruptive option on top of him sniping your coins or your grenades out of the air.

**Comment by eternalUnion** [comment]
Issue with v2 chargebacking is the fact that there can be a chain of chargebacks where player and v2 constantly chargeback the same coin, which could theoretically go on forever. It could be that I misread what you wrote, I could not understand well. I assume you are meaning if v2 throws a coin, and the player shoots it too early (which is already too hard when fast coining is enabled), v2 should be able to chargeback it. The problem is coin you shoot turns into a hitscan, while v2's is a projectile. I am not too sure this feature needs a little bit more detailed description for me to implement it.

**Comment by PrinceKasaii** [comment]
I imagine it won't happen as often with him fast coining, but rather he'll try to purposefully use them to chargeback you.

You know how when against sentries in cybergrind, players sometimes jump backward, look down, and throw a coin in front of them in a way that it stays in between V1 and the sentry's line of sight while they're moving? This way they can chargeback the sentry and dodge other enemies firing at them at the same time.

The idea is that V2 could - by chance or on a cooldown - react to you attacking him with a hitscan weapon. He could jump backward the same way and throw a coin in front of him as soon as you swap to that weapon, if you hit him with too many of them in a row, or on reaction to you throwing a coin yourself instead of just shooting it. When he does this he would deliberately wait to shoot the coin. This way the coin defends him from whatever hitscan weapon you were currently trying to shoot him with.

**Comment by eternalUnion** [comment]
Unfortunately this tech is both exploitable (since v2 throwing a coin on a known event like revolver draw is a source of free coins) and hard to implement since it requires rewriting v2's and v1's interaction with coins as well as other issues stated above.
