### ISSUE TITLE
[FEATURE] Hard Damage Spawn

### ISSUE THREAD

**Issue by Holawenasx2** [eternalUnion/UltraPain#21]
# Feature
So the idea is copy the effect of the Flesh Panopticon Spawn (the eyes) into an enemy (Maybe the Mal Face, the Ferryman or any other enemy that is weak)

# Usage
This change would mostly first of all: Change how people fight, as the Ferryman and the Mal face are actual menaces, adding the effect from the Flesh Panopticon would be an scary buff
# Extras
also maybe angering enemies could enable radiance on them.

**Comment by eternalUnion** [comment]
From the wiki:
`The Panopticon will summon a number of minions, which depends on difficulty level and phase. While there is at least 1 minion alive, V1 will be continuously inflicted with hard damage, making any damage sustained impossible to heal back until all eye minions are killed.
`
This could make most of the difficulties unsustainable, because at some point it becomes nearly impossible to avoid getting damaged. And having hard damage is a virtual hard sentence in some of the presets.

**Comment by Holawenasx2** [comment]
maybe the effect could be instead of instant hard damage, the hard damage could increase slowly if the enemy is present, maybe idk, stalkers having this ability can be destructive

**Comment by UntotenTheo** [comment]
Hard damage is already bad enough on default ULTRAPAIN, given how 50% of damage taken is turned into Hard Damage because it uses the ULTRAKILL MUST DIE Difficulty Slot, this would unfortunately just make the issue worse.

In the Campaign it may be reasonable to an extent, as Malicious Faces only spawn in groups of 3 at most, and the Ferryman only appears in 2 levels, but that's assuming the effect doesn't stack, which it shouldn't otherwise things'll get bad really, really quickly.

If we take the Cyber Grind into account though, things get pretty dicey, I've personally seen an all-time high of 10 Malicious Faces and I think 4 Ferrymen throughout my time playing the Cyber Grind, that basically ensures any and all damage you take is going to be permanent, and while I'm no expert on balance (Hell, I'm the creator of the System Overload preset, I don't know anything about balance) I do think its pretty unfair since an enemy simply exists.

I get that you shouldn't be taking damage in the first place, but that's easier said than done, you already have 50% of all damage taken being converted into Hard Damage, I don't think you need any more than that.

It works for the Flesh Panopticon fight because its a boss exclusive gimmick, any damage you took beforehand or will take is going to be even more detrimental than usual because its, well, a boss (but this is balanced by the fact that the Golden Eyes are jackshit easy to kill)

But giving such a powerful ability (even if it isn't at full strength) to a Non-Boss enemy just seems pretty broken.

**Comment by eternalUnion** [comment]
Not planning to implement this unless it can still make the gameplay sustainable. If this feature is implemented, every encounter would have to be nearly perfect no hit run.
