### ISSUE TITLE
[FEATURE] Make virtue insignia last longer

### ISSUE THREAD

**Issue by Brishenn** [eternalUnion/UltraPain#27]
# Feature
"If a Virtue is to be given more than 1 "charge" of its light beam attack (through third-party software like Unity Explorer), the glyphs to summon light beams will turn blue."
Is it possible for this to be added as a config? Have them do the attack twice, or is this not possible?

# Usage
Well, makes virtues harder lmao. Could also be applied to Flesh prison's big beams so that they linger even longer, same with Panopticon's. Or even for if you activate insignia for Hideous Masses.

# Extras
Idk, make Virtue's cores explode like a Sisyphus explosion?

**Comment by eternalUnion** [comment]
There is a charge field for insignia, but only place I saw it got used is flesh prisons. Their attacks actually spawn a single insignia with 3 charges and once the first one is fired another insignia with 2 charges is spawned etc. Though virtues already fire at a very rapid rate, especially when enraged to a point they come back to back. Making insignia last longer could be a better way to make virtues more threatening though

Explosion could be a problem, because virtues are usually killed close-range with whiplash and the core could be accidently destroyed

**Comment by Brishenn** [comment]
Huh, I see. Looks like I'll be disproving the trivia then. Making the insignia last longer could be a good idea,

**Comment by eternalUnion** [comment]
https://github.com/eternalUnion/UltraPain/releases/tag/fr27-1.0.2-0 this release provides an insignia length multiplier field which can make insignia last longer/shorter

**Comment by eternalUnion** [comment]
Note: This could be implemented for hideous mass as well, giving it more area denial ability
