### ISSUE TITLE
Screwdriver Rework

### ISSUE THREAD

**Issue by EvolutioLunky** [eternalUnion/UltraPain#3]
# Feature
I don't entirely know how ULTRAKILL works on the inside but I have ideas for how to fix screwdriver.
1st of all, the screwdrivers main issue is its inability to interact with any other weapon.
You cant parry it if its not in an enemy, it cant hit rockets, grenades or anything like that, and it doesn't stick into walls.
I think it should be able to split coins into a configurable number of coin fragments that do less damage but you have more coins to shoot/combo off of.
it should also stick into walls and be parryable from that but it loses its total projectile lifetime when doing so (as in its not as sharp anymore). as well as the ability to parry it midair.
Also it could maybe split grenades into cluster bombs, and rockets (or cannon balls) into shrapnel.
It should also just straight up let it interact with magnets.

# Usage
this just generally fixes the entirety of the screwdrivers' problems. making it viable anywhere in the game. especially bosses though due to the coin splitting. (railcoin opportunities)

# Extras
general configuration of damage, style, coin fragment (and other fragments), and other stuff like that would be nice.

**Comment by eternalUnion** [comment]
Interesting idea, though screwdriver sticking to a wall doesn't make much sense cause you cannot parry it out of a wall (since you will be looking at the wall). Screw driver making stuff split actually makes sense, such as hitting grenade with the screwdriver which would "split" it (maybe clusters can even auto-aim like coins). Magnets, I don't know how it could be implemented mechanic wise but with a little bit more thinking I think this can be implemented.

**Comment by eternalUnion** [comment]
https://github.com/eternalUnion/UltraPain/assets/30156046/992b5f8a-fbb2-418c-a8a4-a7d85836ca52

**Comment by eternalUnion** [comment]
https://github.com/eternalUnion/UltraPain/assets/30156046/bdf9fed4-c611-402c-9e40-4aa2cb5e6da4

Grenades auto-aim if an enemy is present

**Comment by eternalUnion** [comment]
Second revision: https://github.com/eternalUnion/UltraPain/releases/tag/fr3-1.0.2-1
* Screw drivers can now home towards enemies with magnets if parried

**Comment by EvolutioLunky** [comment]
bro that's awesome. thanks man. also the projectile is long enough (like a magnet) to stick out of a wall to be parried. but this is so cool!

**Comment by eternalUnion** [comment]
I don't think it is worth it because the drill must be at the eye level of the player to even have the opportunity to send it to an enemy. Even then, the player must either be clipping trough the drill and look backward or parry 90 degrees left/right to the wall. It is just way too conditional. Only way it could work is to implement the homing ability of the drill to wall punching.

Another idea I have is making the drill home towards magneted enemies when player kills the enemy with the drill attached. That way, the drill could be "juggled" between enemies.

**Comment by EvolutioLunky** [comment]
I see. I didn't know that's how ULTRAKILL parries work. also the latter idea of 'juggling' sounds awesome.

**Comment by EvolutioLunky** [comment]
Also you should add style config for the screwdriver's splitting abilities to complete the rework I guess.

Also keep up the work! You've made one of my favorite mods for ULTRAKILL and I've had tons of fun with this addition already.

**Comment by EvolutioLunky** [comment]
@eternalUnion I have made an example using magnets on how it could be useful to stick it in walls. (sorry if I'm seeming pushy I don't mean it)

https://github.com/eternalUnion/UltraPain/assets/112786974/8b4c3e5f-f726-4fba-9d45-8ae281aabcfd

the first clip is because its timer is paused i can get another railgun charge and thus do that.

**Comment by eternalUnion** [comment]
I guess I could try to make it work

**Comment by EvolutioLunky** [comment]
Also I found a bug. (that to be quite frank is brutal to utilize)

https://github.com/eternalUnion/UltraPain/assets/112786974/a5b4c88b-ab43-42d6-b99a-5325ff6e8fb3

@eternalUnion
