### ISSUE TITLE
[FEATURE] Player stat config

### ISSUE THREAD

**Issue by EvolutioLunky** [eternalUnion/UltraPain#36]
# Feature
allow for editing of the players stats, like max health, move speed, damage multiplier, max speed cap, possibility of regeneration (health regen), weapon damage (individually, including feedbacker, magnets, coins, and KB), size, and self damage multiplier.

# Usage
general suffering or customization of the player.

# Extras
possibly the ability to change V1's colors (including coins, projectiles, and arms)

sort of building off of the weapon cooldown config suggestion but more into the player stats.

**Comment by UntotenTheo** [comment]
Player stat changing could be interesting, but I feel like having some of these (and having too much) would be overkill.

Max Health might be the best contender to be added, though it should be kept in mind that Hard Damage isn't taken above 100.

Move Speed could be boiled down to Walk Speed, Dash Speed and Slide Speed, Jump Speed and Slam Speed, but given all of the relatively easy moves you can do to gain high speed, I don't think this'll be necessary.

Damage Multiplier, maybe, but if you want an enemy to die faster you can just set its Health Multiplier in the config to be lower than 1.
(Alternatively utilize weaknesses against enemies because every Non-Boss enemy is pretty flimsy all things considered)

I don't think theres a Maximum Speed Limit, this can easily be observed by stacking Idols in one spot using the Spawner Arm, then using the Kill All Enemies cheat to detonate all of them at the same time, alternatively, using the Sonic Reverberator from the UltraFunGuns mod at maximum charge, aiming downwards then firing.

Adding Regeneration would just incentivize stalling until you heal, while it would be useful for hectic arenas (Such as the end of 4-3), I feel like it should just be a Hard Damage% changer instead, giving the player more survivability but still making sure that if they play carelessly, they'll be brought to a swift end regardless.

Weapon Damage has too many things to consider, I don't think it should be added.

Self Damage Multiplier feels unnecessary considering if you whiff an Overpump Explosion you lose half of your total Health

**Comment by eternalUnion** [comment]
Since they are so similar, some of these changes may be used in #26

**Comment by eternalUnion** [comment]
https://github.com/eternalUnion/UltraPain/releases/tag/fr26-1.0.2-1
This build contains the features for health and hard damage modifications (as well as the previous features from cooldown)
Not thinking of implementing damage intake modifier as enemy stat editor can already do that
Also not thinking of implementing damage output modifier as 1 - just change the health and 2 - there will be a weakness editor

**Comment by EvolutioLunky** [comment]
the reason for the damage config is if for instance i was trying to make the rail cannon a high fire rate low damage weapon, increasing all enemy stats would be overkill and make other weapons weaker. and resistances reduces the damage of lightning (from 5-2 and 5-4). so modifying the damage of the weapon is the only option. also just for the sake of customization.

also the self damage modifier is for explosions and such so you could reduce the amount of damage you take from a 4 pump shotgun explosion, or core eject, or even the rocket launcher.

the regen could be used for negative damage (forcing you to always be moving). 

also size could be very funny (as in just making v1 the size of cancerous rodent and having to fight things 5 times your size).

I included magnets on the damage config because they can go right though someone (not all the way but yeah) and do 0 damage. and yet the whiplash does damage and does not go through them.

also changing v1's colors would be pretty awesome.

**Comment by eternalUnion** [comment]
That makes sense. I will add weapon damage modifications (which might take a while) and hp regen (amount of time, regen amount [+/-], minimum/maximum health limit [maybe to limit the max natural regen/decay], toggle on level/secret level/misc levels[sandbox + credits]). I will leave v1 coloring to other mods (tho how could it be colored while we can't see it?). I don't know about size, may require some tests.

**Comment by eternalUnion** [comment]
https://github.com/eternalUnion/UltraPain/releases/tag/fr26-1.0.2-2
This version contains modifications for the revolver. It took a while because I had to learn a new technique to modify it. Other weapons will probably be implemented faster

**Comment by eternalUnion** [comment]
https://github.com/eternalUnion/UltraPain/releases/tag/fr26-1.0.2-3
Shotgun modifications
Only problem is player getting the same damage even from farther distances (and possible compability issues)

**Comment by eternalUnion** [comment]
https://github.com/eternalUnion/UltraPain/releases/tag/fr26-1.0.2-4
Contains nailgun/saw launcher modification as well as hp decay/regen feature
