### ISSUE TITLE
Enemies that shoot hitscans target coins

### ISSUE THREAD

**Issue by I-am-become-stupid** [eternalUnion/UltraPain#60]
# Feature
Normally when an enemy hitscan hits a coin, it chargebacks. This new feature could make it so that when it hits a coin, it still targets the player. Even enemies that this applies to will aim for coins if there are any.

# Usage
Let's say someone decides he's gonna try to chargeback a malicious face. But when the hitscan beam hits the coin, it instead targets them.

Or someone's trying to railcoin something with a sentry on the field. He doesn't notice the sentry, he tosses a coin, the sentry shoots the coin, the coin bounces onto another coin, causing a deadcoin sorta thing where the damage is added, and he dies.

# Extras
This feature would normally be just a checkbox, but for maurice, it could have a second checkbox for coin tracking(basically continuing to move after the beam is charged), and if there is a separate checkbox for player tracking, it could also track coins.

**Comment by eternalUnion** [comment]
I don't really want to implement this idea, because Ultrapain is supposed to provide attack opportunities while making the game harder. For example sharpshooting the stray projectile or solider projectile spam, drone beam chargebacks, making cerberus more dangerous at close range but providing parry opportunities, more frequent ferryman attacks but more parry opportunities in a smaller timeframe

Making enemy beams only target player not only cancels a mechanic, but also doesn't provide any chances to use it against enemies
